name: Build

on:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE*'
  pull_request:

jobs:
  build-linux:
    name: Build
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/386
          - linux/arm/v7
          - linux/arm64/v8
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run: docker build --target export --output build . --platform ${{ matrix.platform }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build

  release:
    name: Release
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [ build-linux ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: List artifacts
        run: ls -R artifacts
      # - name: Rename artifacts
      #   working-directory: artifacts
      #   run: |
      #     mkdir ../out
      #     for i in */*/$BUILD_PROFILE/$CARGO_BIN_NAME*; do
      #       mv "$i" "../out/$(sed -E "s/([^/]+)\/[^/]+\/$BUILD_PROFILE\/($CARGO_BIN_NAME)/\2-\1/" <<< "$i")"
      #     done
      #     ls -R ../out
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: out/*
